#Lab 1 sql joins

#1 List the number of films per category

SELECT name AS category_name, COUNT(f.film_id) AS number_of_films
FROM category c
INNER JOIN film_category fc 
ON c.category_id = fc.category_id
INNER JOIN film f 
ON fc.film_id = f.film_id
GROUP BY c.name
ORDER BY number_of_films DESC;


# 2 Retrieve the store ID, city, and country for each store.

SELECT store_id, city, country
FROM store s
INNER JOIN address a ON s.address_id = a.address_id
INNER JOIN city ci ON a.city_id = ci.city_id
INNER JOIN country co ON ci.country_id = co.country_id;


#3 Calculate the total revenue generated by each store

SELECT s.store_id, SUM(p.amount) AS total_revenue
FROM store s
INNER JOIN staff st ON s.store_id = st.store_id
INNER JOIN payment p ON st.staff_id = p.staff_id
GROUP BY s.store_id;


#4 Determine the average running time of films for each category


SELECT c.name AS category_name, AVG(f.length) AS average_running_time
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
JOIN film f ON fc.film_id = f.film_id
GROUP BY c.name
ORDER BY average_running_time DESC;







